export const skills = [
  { id: 0, name: "HTML", icon: "https://img.icons8.com/color/48/html-5--v1.png" },
  { id: 1, name: "CSS", icon: "https://img.icons8.com/color/48/css3.png" },
  { id: 2, name: "JAVASCRIPT", icon: "https://img.icons8.com/color/48/javascript--v1.png" },
  { id: 3, name: "TAILWIND CSS", icon: "https://img.icons8.com/color/48/tailwind_css.png" },
  { id: 4, name: "FIGMA", icon: "https://img.icons8.com/color/48/figma--v1.png" },
  { id: 5, name: "GIT", icon: "https://img.icons8.com/color/48/git.png" },
  { id: 6, name: "JAVA", icon: "https://img.icons8.com/?size=100&id=13679&format=png&color=000000" },
  { id: 7, name: "GITHUB", icon: " https://img.icons8.com/?size=100&id=12599&format=png&color=000000" },
  { id: 8, name: "REACT JS", icon: "https://img.icons8.com/?size=100&id=YYYhFVbH4vFv&format=png&color=000000" },
  { id: 9, name: "SQL", icon: "https://img.icons8.com/?size=100&id=Ign0QG33bZzq&format=png&color=000000" },
  { id: 10, name: "MONGO Db", icon: "https://img.icons8.com/?size=100&id=bosfpvRzNOG8&format=png&color=000000" },
];

export const projectList = [
  {
    id: 0,
    title: "Calculator",
    description: "The calculator design is inspired by Iphone calculator, able to perform basci calculation also includes the scientific operator and functions",
    demoUrl: "link",
    codeUrl: "https://github.com/KGOSIYAGAE/Calculator-version-2",
    img: "/projects-img/Calculator_v2.PNG",
  },
  {
    id: 1,
    title: "LAPTOP AOD GENERATOR",
    description: "A Web App designed to automate the process of completing the AOD, reducing students and staff error on the form. Designed using HTML, JS and CSS",
    demoUrl: "link",
    codeUrl: "https://github.com/KGOSIYAGAE/SPU-Doc-Generator",
    img: "/projects-img/spu_doc_gen.PNG",
  },
  {
    id: 2,
    title: "Weather App v1",
    description: "Weather app that uses a weather api to give in short details weather of the city the user chooses to search on that particular day.",
    demoUrl: "link",
    codeUrl: "https://github.com/KGOSIYAGAE/weatherApp",
    img: "/projects-img/Weather_App_v1.PNG",
  },
  {
    id: 3,
    title: "Weather App v2",
    description: "Updated version of the Weather App v1, providing user in details the weather details for that day of search, also providing summary the weeks weather.",
    demoUrl: "link",
    codeUrl: "https://github.com/KGOSIYAGAE/Weather-App-V2",
    img: "/projects-img/Weather_App_v2.PNG",
  },
  {
    id: 4,
    title: "Book Store",
    description: "MERN Stack application that allow you to view books stored in the database, also be able to perform basic functions such as create, update, and delete a book. ",
    demoUrl: "link",
    codeUrl: "https://github.com/KGOSIYAGAE/BOOK_STORE_MERN",
    img: "/projects-img/MERN Stack Books.PNG",
  },
  {
    id: 5,
    title: "Notes App",
    description: "MERN Stack application that allow the user to create, update and delete notes in the database, using MongoDB and token authorization. ",
    demoUrl: "link",
    codeUrl: "https://github.com/KGOSIYAGAE/MERN-Notes-App",
    img: "/projects-img/MERN Stack Notes App.PNG",
  },
];
